Some tidy up and trying a different approach
phocassoftware/graphql-dyanmodb-manager pull request #2
Opened 2021-02-03 04:17 UTC by tomvarley

Hey @ashley-taylor 

Hopefully this is what you were after in terms of the right place to put a pull request.

Happy to walk you through anything you need.

Thanks for looking!

Tom

2021-02-08 23:28 UTC, ashley-taylor requested changes
looking good. Few things I would change

2021-02-08 23:28 UTC, ashley-taylor commented on graphql-database-manager-dynamo/src/main/java/com/fleetpin/graphql/database/manager/dynamo/DynamoDb.java
> +    public CompletableFuture<List<BackupDynamoItem>> restoreBackup(List<BackupDynamoItem> entities) {
Will want to make use of the dynamo batch put operation for this. Be way faster.

2021-02-08 23:28 UTC, ashley-taylor commented on graphql-database-manager-dynamo/src/main/java/com/fleetpin/graphql/database/manager/dynamo/TableUtil.java
> +			if(field.getKey().equals("links")){
This would break if a custom object contained a field called links,

2021-02-09 00:09 UTC, tomvarley commented on graphql-database-manager-core/pom.xml
> +        <dependency>
Possibly an artifact from when I was trying some other stuff. Removed, thanks.

2021-02-09 00:09 UTC, tomvarley commented on graphql-database-manager-core/src/main/java/com/fleetpin/graphql/database/manager/Database.java
> +	public CompletableFuture<List<BackupDynamoItem>> makeBackup(String organisationId) {
Updated

2021-02-09 00:11 UTC, tomvarley commented on graphql-database-manager-core/src/main/java/com/fleetpin/graphql/database/manager/util/BackupDynamoItem.java
> +	public String getField(String tableTarget) {
Not any more I think, sorry I should have removed! Done so now.

2021-02-09 02:01 UTC, tomvarley commented on graphql-database-manager-dynamo/src/main/java/com/fleetpin/graphql/database/manager/dynamo/TableUtil.java
> +			if(field.getKey().equals("links")){
I agree, but I am unsure how else to get this attribute to know to treat it specially. This is also what is done in other places (DynamoItem.java, although it is for just the top level I guess)

2021-02-09 02:02 UTC, tomvarley commented on graphql-database-manager-dynamo/src/main/java/com/fleetpin/graphql/database/manager/dynamo/DynamoDb.java
> +    public CompletableFuture<List<BackupDynamoItem>> restoreBackup(List<BackupDynamoItem> entities) {
Updated (I think)

2021-02-09 02:06 UTC, tomvarley commented on graphql-database-manager-core/pom.xml
> +        <dependency>
Nope, I was wrong! This is because I am using AttributeValue in BackupDynamoItem, might need some advice on the cleanest way of tidying that up

2021-02-09 02:38 UTC, tomvarley commented on graphql-database-manager-core/pom.xml
> +        <dependency>
Have refactored now

2021-02-09 04:04 UTC, tomvarley commented on graphql-database-manager-dynamo/src/main/java/com/fleetpin/graphql/database/manager/dynamo/TableUtil.java
> +			if(field.getKey().equals("links")){
Have tried to separate the logic a bit more now, and the method is specific to Backup now

2021-02-15 02:27 UTC, ashley-taylor requested changes
few little things.

2021-02-25 22:51 UTC, tomvarley commented on graphql-database-manager-dynamo/src/main/java/com/fleetpin/graphql/database/manager/dynamo/DynamoBackupItem.java
> +		ObjectMapper om = new ObjectMapper();
Good point! Have refactored to now pass this in when it is called

2021-02-25 22:53 UTC, tomvarley commented on graphql-database-manager-dynamo/src/main/java/com/fleetpin/graphql/database/manager/dynamo/TableUtil.java
> +	public static <T> T convertTo(ObjectMapper mapper, AttributeValue attributeValue, Class<T> type) {
Not any more! Updated

2021-03-16 00:13 UTC, ashley-taylor approved these changes

2021-03-16 01:28 UTC, merged